<?php

namespace App\Services;

use App\Constants\StatusConstant;
use App\Exceptions\SystemException;
use App\Helpers\QueryHelper;
use App\Models\Certificate;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

/**
 * @Author apple
 * @Date   Sep 30, 2021
 */
class CertificateService extends BaseService
{
    protected array $status = [StatusConstant::PROCESS, StatusConstant::PROCESSED];

    function createModel(): void
    {
        $this->model = new Certificate();
    }

    public function getAll(): LengthAwarePaginator
    {
        $this->preGetAll();
        $data = $this->queryHelper->buildQuery($this->model)->with(['specializes']);
        try {
            $response = $data->paginate(QueryHelper::limit());
            $this->postGetAll($response);
            return $response;
        } catch (Exception $e) {
            throw new SystemException($e->getMessage() ?? __('system-500'), $e);
        }
    }

    public function storeRequestValidate(object $request, array $rules = [], array $messages = []): bool|array
    {
        $rules = [
            'name' => 'required|max:100',
            'image' => 'required',
            'specialize_id' => 'required|number',
        ];
        $messages = [
            'name.required' => 'Hãy nhập tên chứng chỉ !',
            'name.max' => 'Tên chứng chỉ không quá 100 ký tự !',
            'image.required' => 'Hãy nhập ảnh !',
            'specialize_id.required' => 'Hãy chọn chuyên môn của chứng chỉ !',
            'specialize_id.number' => 'Hãy nhập Specialize gồm các chữ số !',
        ];

        return parent::storeRequestValidate($request, $rules, $messages); // TODO: Change the autogenerated stub
    }


    public function updateRequestValidate(int|string $id, object $request, array $rules = [],
                                          array $messages = []): bool|array
    {
        $rules = [
            'name' => 'required|max:100',
            'image' => 'required',
            'specialize_id' => 'required|number',
        ];
        $messages = [
            'name.required' => 'Hãy nhập tên chứng chỉ !',
            'name.max' => 'Tên chứng chỉ không quá 100 ký tự !',
            'image.required' => 'Hãy nhập ảnh !',
            'specialize_id.required' => 'Hãy chọn chuyên môn của chứng chỉ !',
            'specialize_id.number' => 'Hãy nhập Specialize gồm các chữ số !',
        ];

        return parent::updateRequestValidate($id, $request, $rules, $messages); // TODO: Change the autogenerated stub
    }

}
