<?php

namespace App\Services;

use App\Constants\StatusConstant;
use App\Exceptions\BadRequestException;
use App\Models\Comment;
use App\Models\CourseStudent;
use Illuminate\Validation\Rule;
use Exception;

class CommetnService extends BaseService
{
    protected array $status = [StatusConstant::ACTIVE, StatusConstant::INACTIVE];

    function createModel(): void
    {
        $this->model = new Comment();
    }

    public function storeRequestValidate(object $request, array $rules = [], array $messages = []): bool|array
    {
        $rules = [

            'id_course' => 'required|exists:courses,id',
            'user_id' => 'required|exists:users,id',
            'content' => 'required|max:255',
            'number_stars' => 'required|numeric'
        ];
        $messages = [
            'id_course.required' => 'Hãy chọn khóa học !',
            'id_course.exists' => 'Khóa học này không tồn tại tồn tại !',
            'user_id.required' => 'Xin mời bạn đăng nhấp !',
            'user_id.exists' => 'Người dùng không tồn tại !',
            'content.required' => 'Hãy nhập nội dung cho bình luận !',
            'content.max' => 'Nội dung không được quá 255 ký tự  !',
            'number_stars.required' => 'Hãy đánh giá sao cho khóa học !',
            'number_stars.numeric' => 'Bạn nhập số sao không đúng giá trị !',
        ];

        return parent::storeRequestValidate($request, $rules, $messages); // TODO: Change the autogenerated stub
    }

    public function preAdd(object $request)
    {
        if ($request != "") {
            $check = CourseStudent::where('user_id', $request->user_id)->where('course_id', $request->id_course)->where('status', StatusConstant::COMPLETE)->first();
            if (!$check) {
                throw new BadRequestException(
                    ['message' => __("Bạn không thể đáng giá được khóa học này !")],
                    new Exception()
                );
            }
        }
    }
}
