<?php
namespace App\Services;
use App\Models\CustomerLevel;

/**
 * @Author apple
 * @Date   Sep 30, 2021
 */
class CustomerLevelService extends BaseService{

    function createModel(): void
    {
        $this->model = new CustomerLevel();
    }

    public function storeRequestValidate(object $request, array $rules = [], array $messages = []): bool|array
    {
        $rules = [
            'name' => 'required|min:3|unique:customer_levels,name',
        ];
        return parent::storeRequestValidate($request, $rules, $messages); // TODO: Change the autogenerated stub
    }

    public function updateRequestValidate(int|string $id, object $request, array $rules = [],
                                          array      $messages = []): bool|array
    {
        $rules = [
            'name' => "required|min:3|unique:customer_levels,name,$id",
        ];
        return parent::updateRequestValidate($id, $request, $rules, $messages); // TODO: Change the autogenerated stub
    }
}
