<?php

namespace App\Services;

use App\Models\Demo;

/**
 * @Author apple
 * @Date   Sep 27, 2021
 */
class DemoService extends BaseService
{

    function createModel(): void
    {
        $this->model = new Demo();
    }

    public function storeRequestValidate(object $request, array $rules = [], array $messages = []): bool|array
    {
        $rules = [
            'name' => 'required|unique:demo,name',
            'price' => 'required|integer|min:0',
        ];
        return parent::storeRequestValidate($request, $rules, $messages); // TODO: Change the autogenerated stub
    }

    public function updateRequestValidate(int|string $id, object $request, array $rules = [],
                                          array      $messages = []): bool|array
    {
        $rules = [
            'name' => "required|unique:demo,name,$id",
            'price' => 'required|integer|min:0',
        ];
        return parent::updateRequestValidate($id, $request, $rules, $messages); // TODO: Change the autogenerated stub
    }
}
