<?php

namespace App\Services;

use App\Constants\StatusConstant;
use App\Models\Setting;

/**
 * @Author apple
 * @Date   Sep 30, 2021
 */
class SettingService extends BaseService
{

    protected array $status = [StatusConstant::ACTIVE, StatusConstant::INACTIVE];

    function createModel(): void
    {
        $this->model = new Setting();
    }

    public function storeRequestValidate(object $request, array $rules = [], array $messages = []): bool|array
    {
        $rules = [
            'config_key' => 'required|unique:settings,config_key',
            'config_value' => 'required',
            'status' => 'required|in:' . implode(',', $this->status),
        ];
        $messages = [
            'config_key.required' => 'Hãy nhập tên trường !',
            'config_key.unique' => 'Trường này đã tồn tại !',
            'config_value.required' => 'Hãy nhập giá trị cho trường !',
            'status.required' => 'Hãy chọn trạng thái hoạt động !',
            'status.in' => 'Trạng thái hoạt động không hợp lệ !'
        ];

        return parent::storeRequestValidate($request, $rules, $messages); // TODO: Change the autogenerated stub
    }

    public function updateRequestValidate(int|string $id, object $request, array $rules = [],
                                          array      $messages = []): bool|array
    {
        $rules = [
            'config_key' => "required|unique:settings,config_key,$id",
            'config_value' => 'required',
            'status' => 'required|in:' . implode(',', $this->status),
        ];

        $messages = [
            'config_key.required' => 'Hãy nhập tên trường !',
            'config_key.unique' => 'Trường này đã tồn tại !',
            'config_value.required' => 'Hãy nhập giá trị cho trường !',
            'status.required' => 'Hãy chọn trạng thái hoạt động !',
            'status.in' => 'Trạng thái hoạt động không hợp lệ !'
        ];

        return parent::updateRequestValidate($id, $request, $rules, $messages); // TODO: Change the autogenerated stub
    }
}
