<?php

namespace App\Services;

use App\Constants\StatusConstant;
use App\Models\Slide;

/**
 * @Author apple
 * @Date   Oct 01, 2021
 */
class SlideService extends BaseService
{
    protected array $status = [StatusConstant::ACTIVE, StatusConstant::INACTIVE];


    function createModel(): void
    {
        $this->model = new Slide();
    }

    public function storeRequestValidate(object $request, array $rules = [], array $messages = []): bool|array
    {
        $rules = [
            'name'          => 'required|unique:slides,name',
            'image'         => 'required',
            'alt'           => 'required',
            'status'        => 'required|in:' . implode(',', $this->status),
            'link'          => 'required',
            'title'         => 'required',
            'short_content' => 'required|min:3',
            'content'       => 'required|min:3'
        ];

        return parent::storeRequestValidate($request, $rules, $messages); // TODO: Change the autogenerated stub
    }

    public function updateRequestValidate(int|string $id, object $request, array $rules = [],
                                          array      $messages = []): bool|array
    {
        $rules = [
            'name'          => "required|unique:slides,name,$id",
            'image'         => 'required',
            'alt'           => 'required',
            'status'        => 'required|in:' . implode(',', $this->status),
            'link'          => 'required',
            'title'         => 'required',
            'short_content' => 'required|min:3',
            'content'       => 'required|min:3'
        ];
        return parent::updateRequestValidate($id, $request, $rules, $messages); // TODO: Change the autogenerated stub
    }
}
