<?php

namespace App\Services;

use App\Constants\StatusConstant;
use App\Models\Slide;

/**
 * @Author apple
 * @Date   Oct 01, 2021
 */
class SlideService extends BaseService
{
    protected array $status = [StatusConstant::ACTIVE, StatusConstant::INACTIVE];


    function createModel(): void
    {
        $this->model = new Slide();
    }


    public function storeRequestValidate(object $request, array $rules = [], array $messages = []): bool|array
    {
        $rules    = [
            'name'   => 'required|unique:slides,name',
            'image'  => 'required',
            'status' => 'required|in:' . implode(',', $this->status),
        ];
        $messages = [
            'name.required'   => 'Hãy nhập tiêu đề cho slide !',
            'name.unique'     => 'Tiêu đề này đã tồn tại !',
            'image.required'  => 'Hãy nhập hình ảnh cho slide !',
            'status.required' => 'Hãy chọn trạng thái hoạt động !',
            'status.in'       => 'Trạng thái hoạt động không hợp lệ !'
        ];

        return parent::storeRequestValidate($request, $rules, $messages); // TODO: Change the autogenerated stub
    }

    public function updateRequestValidate(int|string $id, object $request, array $rules = [],
                                          array      $messages = []): bool|array
    {
        $rules = [
            'name'          => "required|unique:slides,name,$id",
            'image'         => 'required',
            'status'        => 'required|in:' . implode(',', $this->status),
        ];

        $messages = [
            'name.required'   => 'Hãy nhập tiêu đề cho slide !',
            'name.unique'     => 'Tiêu đề này đã tồn tại !',
            'image.required'  => 'Hãy nhập hình ảnh cho slide !',
            'status.required' => 'Hãy chọn trạng thái hoạt động !',
            'status.in'       => 'Trạng thái hoạt động không hợp lệ !'
        ];

        return parent::updateRequestValidate($id, $request, $rules, $messages); // TODO: Change the autogenerated stub
    }
}
