version: "3.1"
networks:
  app-network: null
services:
#  nginx:
#    image: nginx:alpine
#    container_name: Lr-nginx
#    working_dir: '/var/www/html'
#    volumes:
#      - './:/var/www/html'
#      - './nginx-default.conf:/etc/nginx/conf.d/default.conf'
#    ports:
#      - "81:80"
#    depends_on:
#      - php
#      - mysql
#    networks:
#      - app-network

  mysql:
    image: mysql:5.7
    container_name: Lr-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
    networks:
      - app-network

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Lr-php
#    volumes:
#      - './:/var/www/html'
    ports:
      - '9000:8000'
    networks:
      - app-network



