version: "3.1"
services:
  nginx:
    image: nginx:alpine
    container_name: Lr-nginx
    working_dir: '/var/www/html'
    volumes:
      - '/var/www/html'
      - './nginx.conf:/etc/nginx/conf.d/nginx.conf'
    ports:
      - "8000:80"
    depends_on:
      - php
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.5
    container_name: Lr-mysql
    ports:
      - "3308:3306"
    volumes:
      - 'db_data:/var/lib/mysql'
      - '.:/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: workpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Lr-php
    volumes:
      - './backend:/var/www/html'
    ports:
      - '9000:9000'
    networks:
      - app-network

  composer:
    image: composer:alpine
    container_name: Lr-composer
    volumes:
      - './backend:/var/www/html'
    working_dir: '/var/www/html'
    networks:
      - app-network

  npm:
    image: node:alpine
    container_name: Lr-nodejs
    volumes:
      - './backend:/var/www/html'
    working_dir: '/var/www/html'
    networks:
      - app-network



